### ISSUE TITLE
Handlevogn makes the navbar have 2 rows

### ISSUE THREAD

**Issue by alexarntzen** [Nabla-NTNU/nablaweb#541]
When logged in the "handlevogn" link makes the the the navigation bar wrap to 2 rows. This is not nice. 
(Also, the floating number behind the "handevogn" is aligned strangely in my opinion.)
![image](https://user-images.githubusercontent.com/48533802/136805796-1caa3096-9b5e-49a6-b338-2dcbdf3365e4.png)

**Comment by kaprests** [comment]
I think the issue is dependent on screen/window width, for me the navbar is one row at 100% zoom level and browser at full screen width, however I get the two rows if I zoom in or make the browser window narrower. 

It is worth mentioning that I have observed the two row issue also before the shopping cart, so the issue is not fundamentally rooted in the shopping cart (handlevogn), but with the navbar's ability to deal with overfilling/overflow/collapse.
