### ISSUE TITLE
Image overflow in news content. 

### ISSUE THREAD

**Issue by alexarntzen** [Nabla-NTNU/nablaweb#542]
Images in the content of a news article overflow on narrow screens. 
![image](https://user-images.githubusercontent.com/48533802/136807668-e4560741-a5af-4c2b-a6a4-62407034848a.png)

**Comment by QuangDNguyen2211** [comment]
Can you assign me this issue?

**Comment by Northo** [comment]
@QuangDNguyen2211, just to elaborate a bit on what @alexarntzen said: we have some formatting guides for Python code, which are tested for when you push changes to the repository.
For HTML/CSS however, we don't have any official style guide. 

Looking forward to see your contribution, and feel free to ask if there is anything at all!

**Comment by QuangDNguyen2211** [comment]
@alexarntzen @Northo sorry for the tagging. I'm doing this for a project in school, and I get graded whether the pull request get accepted or not. The due date is this Friday, so I would appreciate if you can review my pull request as soon as you can. Thank you

**Comment by Northo** [comment]
Hello again, @QuangDNguyen2211 . No worries with the tagging:)

Unfortunately, I cannot accept your PR (pull request). It does not solve the issue. However, upon looking into the issue now, I see that it would not have been possible for you to solve the issue, as the issue was with code in our database, not in the actual code of the project. If you are interested in the details, in order to understand this better, the issue was that the code in the flatpage defining that page had an error in it. However, thank you for helping us uncover the issue.

I am sorry to hear that your school project depends on your PR being accepted. If it helps at all, you are welcome to cite me in that you did indeed help us with the issue, even though the particular PR you submitted was not accepted. This is not uncommon in open source projects, where the discussion in on the issues are just as valuable as submitting code.

Some further tips for future projects:
- Try to write clear descriptive commit messages, making it easier for the maintainers to see what you have changed. I do not know what Git client you are using, but now the message is simply `Add files via upload`. 
- Attempt to change only the code that you have to change, and not reformat any other code unless it is necessary. Again, this makes it easier for maintainers to see what you have done. I don't know how well you know Git, so if the following is well known for you, I mean it not in a condescending way, only for you to learn: you can see what you have changed either in your Git client or here on GitHub. Your two commits can be seen at 8c5b77e4b21eb and 37c1957b41a4d. As you see, much of the changes are simply formatting changes, ie. putting several lines on the same line, removing spaces and so forth. Try to avoid such changes, as it makes it more difficult for the maintainer to see exactly what you did.

If you have any other questions, please feel free to comment them here.
You are of course also very welcome to test any other issues.
